### ISSUE TITLE
Rules from User

### ISSUE THREAD

**Issue by rimpy-anon** [rimpy-custom/communityRules#457] opened 2022-07-29 11:21 UTC
```
{
	"vexedtrees980.rimuhiversi": {
		"name": ["Rim-Hivers!"],
		"code": ["2506643795"],
		"loadAfter": {
			"regrowth2.extinctanimals": {
				"name": ["ReGrowth Remastered: Extinct Animals"],
				"comment": ["https://steamcommunity.com/workshop/filedetails/discussion/2506643795/3113657065279669011/?ctp=8#c3274690571060222316"]
			}
		},
		"loadBefore": {}
	}
}
```

**Comment by joseasoler** [comment] 2022-07-29 11:22
This is a duplicate of #458, please disregard this one.

**Closed as completed** 2022-08-07 19:36 UTC
Labels: looks good, obsolete
